---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: safeguard-react
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: ganga-test
  url: https://github.com/SafeGuard-Cyber/safeguard-react
